[package]
name = "nanogpt-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
candle-core = {version = "0.6.0"}
candle-nn = "0.6.0"
itertools = "0.13.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
